# Change these first
owner: MyAirplane # Your GitHub organization or username, where this repository lives
repo: status.aogcommunity.org # The name of this repository

sites:
  - name: Dashboard
    url: https://aogcommunity.org
  - name: Backend API
    url: $API_URL
    headers:
      - 'apikey: $API_KEY'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.aogcommunity.org
  logoUrl: https://aogcommunity.org/img/AOGCommunity.org.svg
  hideNavTitle: true # Hide the title
  name: AOGCommunity.org
  introTitle: "System Status"
  introMessage: "Welcome to [AOGCommunity.org](https://aogcommunity.org)'s home for real-time information on system status and security. Here you'll find live and historical data on system performance. If there are any interruptions in service, a note will be posted here."
  navbar:
    - title: Status
      href: /
    - title: Return to Dashboard
      href: https://aogcommunity.org
  css: ".logo img { max-width: 200px }"

i18n:
  footer: Brought to you by [MyAirplane™](https://myairplane.io)

assignees:
  - filtersource
