# Change these first
owner: MyAirplane # Your GitHub organization or username, where this repository lives
repo: status.aogcommunity.org # The name of this repository

sites:
  - name: AOGCommunity.org Dashboard
    url: https://aogcommunity.org
  - name: API Servers
    url: $API_URL

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.aogcommunity.org
#   logoUrl: https://aogcommunity.org/img/AOGCommunity.org.png
  name: AOGCommunity.org
  introTitle: "System Status Page"
  introMessage: "Welcome to AOGCommunity.org's home for real-time information on system status and security. Here you'll find live and historical data on system performance. If there are any interruptions in service, a note will be posted here."
  navbar:
    - title: Status
      href: /
    - title: Go to Dashboard
      href: https://aogcommunity.org

i18n:
  footer: Brought to you by [MyAirplane™](https://myairplane.io)

assignees:
  - filtersource
